import java.util.Random;
import java.util.Scanner;

public class GuessingGame {

    // create a scanner
    Scanner input = new Scanner(System.in);

    // create var
    boolean correctGuess = false;
    int guess = 0;
    int increment = 0;

    // create a constructor
    public GuessingGame () {
        System.out.println("Hello user, What is your name?");
        String name = input.nextLine(); // get name from user

        System.out.println("Welcome " + name + " I'm thinking of a number between 1 and 100.");

        // create and call the Random constructor to get a random number
        Random rand = new Random();

        // chooses the next number generated by rand from the limit of 1 to 100 (bound)
        int num = rand.nextInt(100);

        System.out.println("Try to guess my number.");

        // create a while loop
        while(correctGuess == false) {
            increment += 1;   // counter increase

            // add a try catch statement
            try {
                guess = input.nextInt();  // get int from user
            } catch(Exception e) {
                String badInput = input.next();   // catch if input is not an int
                System.out.println("That’s not an integer, try again");
                continue;                         // continue out of the current loop; go to next
            }

            if( guess > 100 || guess < 1 ) {
                System.out.println("You’re guess is out of range. Please try again.");
            } else if( guess > num ) {
                System.out.println("You’re guess is too high. Please try again.");
            } else if ( guess < num ) {
                System.out.println("You’re guess is too low. Please try again.");
            } else if ( guess == num ) {
                System.out.println("Well done, "+ name +"! You found my number in " + increment + " tries!");
                correctGuess = true;
            }
        }
    }
}
